#!/usr/bin/env sh
set -e

ffmpeg -v quiet -f concat -safe 0 -i playlists/rokkyu_fast -i cover.png -map 0:a -map 1:v -c:a copy -c:v copy -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (front)" -metadata title="1 Rokkyu Fast" -metadata album="Shiken" -metadata artist="Sanshinkai Aikido" -metadata album_artist="Sanshinkai Aikido" -metadata date=$(date +%Y) -metadata TRACK_TOTAL=20 -metadata genre="Spoken" -metadata track=1 mp3/01_rokkyu_fast.mp3 -y
ffmpeg -v quiet -f concat -safe 0 -i playlists/rokkyu_normal -i cover.png -map 0:a -map 1:v -c:a copy -c:v copy -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (front)" -metadata title="2 Rokkyu Normal" -metadata album="Shiken" -metadata artist="Sanshinkai Aikido" -metadata album_artist="Sanshinkai Aikido" -metadata date=$(date +%Y) -metadata TRACK_TOTAL=20 -metadata genre="Spoken" -metadata track=2 mp3/02_rokkyu_normal.mp3 -y

ffmpeg -v quiet -f concat -safe 0 -i playlists/gokyu_fast -i cover.png -map 0:a -map 1:v -c:a copy -c:v copy -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (front)" -metadata title="3 Gokyu Fast" -metadata album="Shiken" -metadata artist="Sanshinkai Aikido" -metadata album_artist="Sanshinkai Aikido" -metadata date=$(date +%Y) -metadata TRACK_TOTAL=20 -metadata genre="Spoken" -metadata track=3 mp3/03_gokyu_fast.mp3 -y
ffmpeg -v quiet -f concat -safe 0 -i playlists/gokyu_normal -i cover.png -map 0:a -map 1:v -c:a copy -c:v copy -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (front)" -metadata title="4 Gokyu Normal" -metadata album="Shiken" -metadata artist="Sanshinkai Aikido" -metadata album_artist="Sanshinkai Aikido" -metadata date=$(date +%Y) -metadata TRACK_TOTAL=20 -metadata genre="Spoken" -metadata track=4 mp3/04_gokyu_normal.mp3 -y

ffmpeg -v quiet -f concat -safe 0 -i playlists/ikkyu_fast -i cover.png -map 0:a -map 1:v -c:a copy -c:v copy -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (front)" -metadata title="11 Ikkyu Fast" -metadata album="Shiken" -metadata artist="Sanshinkai Aikido" -metadata album_artist="Sanshinkai Aikido" -metadata date=$(date +%Y) -metadata TRACK_TOTAL=20 -metadata genre="Spoken" -metadata track=11 mp3/11_ikkyu_fast.mp3 -y
ffmpeg -v quiet -f concat -safe 0 -i playlists/ikkyu_normal -i cover.png -map 0:a -map 1:v -c:a copy -c:v copy -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (front)" -metadata title="12 Ikkyu Normal" -metadata album="Shiken" -metadata artist="Sanshinkai Aikido" -metadata album_artist="Sanshinkai Aikido" -metadata date=$(date +%Y) -metadata TRACK_TOTAL=20 -metadata genre="Spoken" -metadata track=12 mp3/12_ikkyu_normal.mp3 -y

ffmpeg -v quiet -f concat -safe 0 -i playlists/shodan_fast -i cover.png -map 0:a -map 1:v -c:a copy -c:v copy -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (front)" -metadata title="13 Shodan Fast" -metadata album="Shiken" -metadata artist="Sanshinkai Aikido" -metadata album_artist="Sanshinkai Aikido" -metadata date=$(date +%Y) -metadata TRACK_TOTAL=20 -metadata genre="Spoken" -metadata track=13 mp3/13_shodan_fast.mp3 -y
ffmpeg -v quiet -f concat -safe 0 -i playlists/shodan_normal -i cover.png -map 0:a -map 1:v -c:a copy -c:v copy -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (front)" -metadata title="14 Shodan Normal" -metadata album="Shiken" -metadata artist="Sanshinkai Aikido" -metadata album_artist="Sanshinkai Aikido" -metadata date=$(date +%Y) -metadata TRACK_TOTAL=20 -metadata genre="Spoken" -metadata track=14 mp3/14_shodan_normal.mp3 -y

ffmpeg -v quiet -f concat -safe 0 -i playlists/nidan_fast -i cover.png -map 0:a -map 1:v -c:a copy -c:v copy -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (front)" -metadata title="15 Nidan Fast" -metadata album="Shiken" -metadata artist="Sanshinkai Aikido" -metadata album_artist="Sanshinkai Aikido" -metadata date=$(date +%Y) -metadata TRACK_TOTAL=20 -metadata genre="Spoken" -metadata track=15 mp3/15_nidan_fast.mp3 -y
ffmpeg -v quiet -f concat -safe 0 -i playlists/nidan_normal -i cover.png -map 0:a -map 1:v -c:a copy -c:v copy -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (front)" -metadata title="16 Nidan Normal" -metadata album="Shiken" -metadata artist="Sanshinkai Aikido" -metadata album_artist="Sanshinkai Aikido" -metadata date=$(date +%Y) -metadata TRACK_TOTAL=20 -metadata genre="Spoken" -metadata track=16 mp3/16_nidan_normal.mp3 -y

ffmpeg -v quiet -f concat -safe 0 -i playlists/sandan_fast -i cover.png -map 0:a -map 1:v -c:a copy -c:v copy -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (front)" -metadata title="17 Sandan Fast" -metadata album="Shiken" -metadata artist="Sanshinkai Aikido" -metadata album_artist="Sanshinkai Aikido" -metadata date=$(date +%Y) -metadata TRACK_TOTAL=20 -metadata genre="Spoken" -metadata track=17 mp3/17_sandan_fast.mp3 -y
ffmpeg -v quiet -f concat -safe 0 -i playlists/sandan_normal -i cover.png -map 0:a -map 1:v -c:a copy -c:v copy -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (front)" -metadata title="18 Sandan Normal" -metadata album="Shiken" -metadata artist="Sanshinkai Aikido" -metadata album_artist="Sanshinkai Aikido" -metadata date=$(date +%Y) -metadata TRACK_TOTAL=20 -metadata genre="Spoken" -metadata track=18 mp3/18_sandan_normal.mp3 -y

